/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IuGrafica;

import IuGrafica.Login;
import IuGrafica.AppMonitoreo;
import IuGrafica.SimularLlamada;

/**
 *
 * @author 59892
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemLogin = new javax.swing.JMenuItem();
        itemSimularLlamada = new javax.swing.JMenuItem();
        itemMonitoreo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Iniciar");

        itemLogin.setText("Login");
        itemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLoginActionPerformed(evt);
            }
        });
        jMenu1.add(itemLogin);

        itemSimularLlamada.setText("SimularLlamada");
        itemSimularLlamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSimularLlamadaActionPerformed(evt);
            }
        });
        jMenu1.add(itemSimularLlamada);

        itemMonitoreo.setText("Monitoreo");
        itemMonitoreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMonitoreoActionPerformed(evt);
            }
        });
        jMenu1.add(itemMonitoreo);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLoginActionPerformed
        new Login(this, false).setVisible(true);
    }//GEN-LAST:event_itemLoginActionPerformed

    private void itemSimularLlamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSimularLlamadaActionPerformed
        new SimularLlamada(this, false).setVisible(true);
    }//GEN-LAST:event_itemSimularLlamadaActionPerformed

    private void itemMonitoreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMonitoreoActionPerformed
        new AppMonitoreo(this, false).setVisible(true);
    }//GEN-LAST:event_itemMonitoreoActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemLogin;
    private javax.swing.JMenuItem itemMonitoreo;
    private javax.swing.JMenuItem itemSimularLlamada;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
